image: atlassian/default-image:2

pipelines:
  branches:
    develop:
      - step:
          name: build develop branch
          deployment: production
          services:
            - docker
          script:
            # build the images
            - ./build.sh build $DOCKER_USER
            # test the images
            - ./build.sh test
            # log into docker hub
            - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
            # push the images to docker hub
            - ./build.sh publish $DOCKER_USER
