version: '3.1'

services:

  db-mongo:
    build: ./db-mongo
    restart: always

  memcached:
    build: ./memcached
    restart: always

  websrv-flask:
    build: ./websrv-flask
    restart: always
    ports:
      - 80:80
    links:
      - db-mongo
      - memcached
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=main.py
    command: "flask run --host=0.0.0.0 --port=80"
    volumes:
      - ./websrv-flask/app:/app