version: '3.1'

services:

  postgres:
    image: localhost:5000/uc/efla-postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    image: memcached:1.5-alpine
    restart: always

  websrv-flask:
    image: localhost:5000/uc/efla-websrv-flask:latest
    restart: always
    ports:
      - 1337:80
    links:
      - memcached
      - postgres
    volumes:
      - ./websrv-flask/app:/app

  frontend-dev:
    image: localhost:5000/uc/efla-frontend:latest
    volumes:
      - ./frontend/src:/usr/app/src:rw
      - ./frontend/static:/usr/app/static:rw
    ports:
      - 80:80
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend-prod:
    build: ./frontend
    ports:
      - 80:80
    environment:
      - NODE_ENV=production

volumes:
  postgres: