version: '3.1'

services:
  postgres:
    build: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    image: memcached:1.5-alpine
    restart: always

  websrv-flask:
    build: websrv-flask
    restart: always
    links:
      - memcached
      - postgres
    volumes:
      - ./websrv-flask/app:/app

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/app:rw

  nginx:
    build: nginx
    ports:
      - 80:80
    links:
      - websrv-flask
      - frontend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  postgres: