version: '3.1'

services:
  postgres:
    build: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    image: memcached:1.5-alpine
    restart: always

  backend:
    build: backend
    restart: always
    links:
      - memcached
      - postgres
      - xapi-publisher
    volumes:
      - ./backend/app:/app

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/app:rw

  xapi-publisher:
    build: xapi-publisher
    restart: always
    volumes:
      - ./xapi-publisher/app:/app
    links:
      - mongo
      - redis

  redis:
    image: library/redis
    volumes:
      - redis:/data

  mongo:
    image: bitnami/mongodb:3.6
    volumes:
      - mongo:/bitnami

  nginx:
    build: nginx
    ports:
      - 80:80
    links:
      - backend
      - frontend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  postgres:
  mongo:
  redis: