version: '3.1'

services:
  postgres:
    image: yeldir/st3k101-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    image: memcached:1.5-alpine
    restart: always

  backend:
    image: yeldir/st3k101-backend
    restart: always
    links:
      - memcached
      - postgres

  frontend:
    image: yeldir/st3k101-frontend

  nginx:
    image: yeldir/st3k101-nginx
    ports:
      - 80:80
    links:
      - backend
      - frontend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  postgres: