version: '3.1'

services:
  postgres:
    image: yeldir/st3k101-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - postgres:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5-alpine
    restart: always

  backend:
    image: yeldir/st3k101-backend
    restart: always
    links:
      - memcached
      - postgres
      - xapi-publisher

  frontend:
    image: yeldir/st3k101-frontend

  xapi-publisher:
    image: yeldir/st3k101-xapi-publisher
    restart: always
    links:
      - mongo
      - redis

  redis:
    image: library/redis
    volumes:
      - redis:/data

  mongo:
    image: bitnami/mongodb:3.6
    volumes:
      - mongo:/bitnami

  nginx:
    image: yeldir/st3k101-nginx
    ports:
      - 80:80
    links:
      - backend
      - frontend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  postgres:
  mongo:
  redis: