version: '3.1'

services:

  postgres:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    build: ./memcached
    restart: always

  websrv-flask:
    build: ./websrv-flask
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./websrv-flask/app:/app