version: '3.1'

services:

  postgres:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    image: memcached:1.5-alpine
    restart: always

  websrv-flask:
    build: ./websrv-flask
    restart: always
    ports:
      - 1337:80
    links:
      - memcached
      - postgres
    volumes:
      - ./websrv-flask/app:/app

  frontend-dev:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/app/src:rw
      - ./frontend/static:/usr/app/static:rw
    ports:
      - 80:80
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend-prod:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/app/src:rw
      - ./frontend/static:/usr/app/static:rw
      - ./frontend/node_modules:/usr/app/node_modules
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
    command: bash -c "npm run build && node -r esm index.js"
