version: '3.1'

services:
  postgres:
    build: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=kksrk0vv3zigez6
      - POSTGRES_USER=flask
      - POSTGRES_DB=st3k101
    volumes:
      - postgres:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5-alpine
    restart: unless-stopped

  backend:
    build: backend
    env_file:
      - backend.env
    restart: unless-stopped
    links:
      - memcached
      - postgres
      - xapi-publisher

  frontend:
    build: frontend

  xapi-publisher:
    build: xapi-publisher
    restart: unless-stopped
    links:
      - mongo
      - redis

  redis:
    image: library/redis
    restart: unless-stopped
    volumes:
      - redis:/data

  mongo:
    image: bitnami/mongodb:3.6
    restart: unless-stopped
    volumes:
      - mongo:/bitnami

  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - backend
      - frontend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

volumes:
  postgres:
  mongo:
  redis: