FROM tiangolo/uwsgi-nginx-flask:python3.6

ADD ./nginx/conf.d/nginx.conf /etc/nginx/conf.d/header.conf

WORKDIR /app
ADD ./app/requirements.txt /app
RUN pip install -r /app/requirements.txt

COPY ./app /app
RUN pybabel compile -d translations

ENV FLASK_CONFIG_PATH="/app/flask.cfg"
ENV FLASK_APP="main.py"
ENV FLASK_DEBUG="1"
ENV FLASK_ENV="development"

ENV DEBUG="yes"

ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=80"]