default_machine: &default_machine
  machine:
    # might not have any effect, since dlc is a premium feature
    docker_layer_caching: true

version: 2
jobs:
  build:
    <<: *default_machine
    steps:
      - checkout
      - run:
          name: greenkeeper lockfile update
          command: |
            greenkeeper-lockfile-update
      - run:
          name: test images
          command: |
            ./build.sh test
      - run:
          name: greenkeeper lockfile upload
          command: |
            greenkeeper-lockfile-upload
      - run:
          name: build images
          command: |
            ./build.sh build yeldir
  build_and_publish:
    <<: *default_machine
    filters:
      branches:
        only: master
    steps:
      - checkout
      - run:
          name: greenkeeper lockfile update
          command: |
            greenkeeper-lockfile-update
      - run:
          name: test images
          command: |
            ./build.sh test
      - run:
          name: greenkeeper lockfile upload
          command: |
            greenkeeper-lockfile-upload
      - run:
          name: build images
          command: |
            ./build.sh build yeldir
      - run:
          name: login to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push images to docker hub
          command: |
            ./build.sh publish yeldir