default_machine: &default_machine
  machine:
    # might not have any effect, since dlc is a premium feature
    docker_layer_caching: true

version: 2
jobs:
  build:
    <<: *default_machine
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            ./build.sh test
      - run:
          name: build images
          command: |
            ./build.sh build yeldir
      - run:
          name: login to docker hub (if master)
          command: |
            if [[ $CIRCLE_BRANCH -eq "master" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
            else
              echo "Not on master branch. Skipping..."
            fi
      - run:
          name: push images to docker hub (if master)
          command: |
            if [[ $CIRCLE_BRANCH -eq "master" ]]; then
              ./build.sh publish yeldir
            else
              echo "Not on master branch. Skipping..."
            fi