"""v3.0.0-beta

Revision ID: 8d32f2e9269b
Revises: 
Create Date: 2018-10-06 12:07:07.893786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d32f2e9269b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'position')
    op.drop_column('dimension', 'position')
    # ### end Alembic commands ###
