FROM mongo:3.4

COPY ./docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/

ENV MONGO_INITDB_ROOT_USERNAME="iuef7fueqofewwif23o8328fg32fi23gfiugefuhjshsalf"
ENV MONGO_INITDB_ROOT_PASSWORD="due3737t4hwe9829321frwelpwqhwvuzt37r2iqmfblqjre"
ENV MONGO_INITDB_FLASK_USERNAME="iuewewfiqksnsaep384zdnbspa75gfogphuenb"
ENV MONGO_INITDB_FLASK_PASSWORD="uuret37875696nhfoids762632jjsofjf9398g"
ENV MONGO_INITDB_FLASK_DATABASE="efla-web"
